version: '3.8'
volumes:
  psqldata:
  rabbitdata:

services:
  adminer:
    image: adminer
    ports:
      - 8081:8080
    depends_on:
      - db
    links:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_DB: AccountPermissionByPaymentMethod
      POSTGRES_USER: user
      POSTGRES_PASSWORD: passs
    ports:
      - 5432:5432
